### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by anzz1**
Fixes discussed in https://github.com/ThirteenAG/d3d9-wrapper/pull/14

untested, please review and test before merging

### CODE REVIEW

**Comment by ThirteenAG** [comment]
Thanks, I'll get to it as soon as possible.

**Comment by ThirteenAG** [comment]
Worked with SCCT, Scarface but not with Splinter Cell Conviction. Will take a look why.

**Comment by anzz1** [comment]
If you comment out the line [dllmain.cpp#476](https://github.com/anzz1/d3d9-wrapper/blob/a9da4cc9efeb3da2b521fdf451f9b9727637a3e5/source/dllmain.cpp#L476)

```cpp
if ( true /*hWnd == g_hFocusWindow || _fnIsTopLevelWindow(hWnd)*/ ) // skip child windows like buttons, edit boxes, etc.
```

skipping the logic of checking for d3d focuswindow or a top level window (and thus should be applied to all windows registered by the app), see if it'll fix it?

one way could also be to just skip all the logic and just go for the global EAT hook for the funcs and SetWindowsHookEx for all wndprocs. and just not caring about overlays and whatevers, maybe they wouldn't even break if they don't use any focus/activation checking logic.

**Comment by ThirteenAG** [comment]
Don't think it will help, because the problem is just the hooks aren't applied. I'll check though.

**Comment by ThirteenAG** [comment]
Yeah, I've checked, no difference. With uncommented code everything works fine, overlays and such.

**Comment by ThirteenAG** [comment]
Also in case of conviction, I noticed a strange cursor behavior in windowed mode:

https://user-images.githubusercontent.com/4904157/194767230-fd704e46-803c-439d-8d9f-2e9f72ccd9c6.mp4

Does work if game resolution matches desktop resolution.

**Comment by anzz1** [comment]
That's strange, as at a quick glance your new iat hook should achieve exactly the same result as my old one (and more), don't know what it's missing then. 

You even improved upon it, as I noticed the error in my way of doing it as I only checked the ILT (originalfirstthunks by names/ordinals) and did not check the IAT array at all (firstthunks by addresses), as there can be cases where there are functions in the IAT without a matching ILT entry or the ILT could even be completely missing as it is optional by the PE spec.

I don't see what's wrong with a glance, it would need to be debugged using some example where the new way doesn't work to see what exactly happens. But for now, doing the same thing twice doesn't really hurt. It's just a little "messy".

---

For the cursor behaviour thing, I don't really understand what you're trying to show me there :sweat_smile: . What's wrong in that video?

**Comment by ThirteenAG** [comment]
> For the cursor behaviour thing, I don't really understand what you're trying to show me there 😅 . What's wrong in that video?
Cursor is clipped to the area, smaller than game's window. Hence I can't press some buttons located outside of that area.

>I don't see what's wrong with a glance, it would need to be debugged using some example where the new way doesn't work to see what exactly happens. 
Check Splinter Cell Conviction, it's the only one I had issues with. Though currently this implementation works fine everywhere I've tried so far. Especially handy in Scarface, because it always crashes on alt tab.

**Comment by anzz1** [comment]
Yeah doing the iathook twice doesn't really hurt anyway, so it's more of a when can be arsed / have the time issue.

But that cursor thing is an issue indeed. I'll try to look into Splinter Cell Conviction when I have the time. I'm not super familiar with D3D so I don't know whether there is a such a clamp function in D3D itself, or maybe the game simply uses winapi to either ClipCursor to what it thinks is the window rect, or SetCursorPos on the render loop to force the cursor position between specified coordinates. It's probably an easy fix though.

The fix could be actually implemented as a new function, maybe a tri-state config option "ClampCursor" where 0=default/do nothing , 1 = clamp cursor to window when in focus , 2 = always unrestricted. Meaning that the user control how they want it, especially useful in multi-screen environments. As we already are in full control and thus know the focus state, this would be easy to implement.

**Comment by anzz1** [comment]
BTW can you paste exactly the conditions for the problem in SCC to appear, one was to have different resolution in desktop and game, and then the config options used.

**Comment by ThirteenAG** [comment]
> Can you paste exactly the conditions for the problem in SCC to appear, one was to have different resolution in desktop and game, and then the config options used.

I think it works fine if windowed res matches desktop res, but I used to test with 1280x720, that's where the problem appeared. Config is default, apart from windowed mode enabled. It could be the game's issue btw.

**Comment by anzz1** [comment]
I just noticed a problem in the iathook and put PR #17 .

**Comment by anzz1** [comment]
Well I couldn't get Splinter Cell Conviction to run at all, and got instant CTD instead. I read that the servers were put offline, and tried various dodgy fixes found online, to no avail.

**Comment by ThirteenAG** [comment]
Idk, steam version works fine for me. And I have retail too, didn't have problems with it either.

**Comment by anzz1** [comment]
It might me my setup/driver issue then. Lmk if any other example comes up.

**Comment by ThirteenAG** [comment]
> It might me my setup/driver issue then. Lmk if any other example comes up.

Hmm, maybe check this guide?

https://steamcommunity.com/sharedfiles/filedetails/?id=1131135165

**Pull request merged**
